sudo: false
dist: trusty

os:
 - linux
 - osx

language: d

d:
 - dmd-beta
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1
 - dmd-2.073.2
 - dmd-2.072.2
 - dmd-2.071.2
 - dmd-2.070.2
 - dmd-2.069.2
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-beta
 - gdc
 - dmd-beta
 - ldc-beta
 - dmd
 - ldc

matrix:
  allow_failures:
   - d: gdc
   - d: dmd-beta
   - d: ldc-beta

addons:
  apt:
    packages:
      libblas-dev

script:
 - dub test --compiler=${DC}
 - for ex in $(ls -d examples/*/); do dub test --root=$ex --compiler=${DC}; done
