sudo: false
dist: trusty

os:
 - linux
 - osx

language: d

d:
 - dmd
 - ldc
 - dmd-beta
 - ldc-beta
 - gdc

matrix:
  allow_failures:
   - d: gdc
   - d: dmd-beta
   - d: ldc-beta

addons:
  apt:
    packages:
      libblas-dev

script:
 - for ex in $(ls -d examples/*/); do dub test --root=$ex --compiler=${DC}; done
