sudo: false

language: d

d:
 - dmd-2.068.0
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1
 - gdc

addons:
  apt:
    packages:
      libblas-dev

script:
 - dub test --compiler=${DC}
 - for ex in $(ls -d examples/*/); do dub test --root=$ex --compiler=${DC}; done
