sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.069.0-b2
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.16.0
 - ldc-0.15.1
 - gdc-4.9.2
 - gdc-5.2.0

matrix:
  allow_failures:
   - os: osx
     d: gdc-5.2.0
   - os: osx
     d: gdc-4.9.2

addons:
  apt:
    packages:
      libblas-dev

script:
 - dub test --compiler=${DC}
 - for ex in $(ls -d examples/*/); do dub test --root=$ex --compiler=${DC}; done
